import "./globals.css";
import Header from "./Components/Header/Header";
import { Rajdhani, Orbitron } from "next/font/google";
import LeftBar from "./Components/LeftBar/LeftBar";
const rajdhaniFont = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--rajdhani-font",
});

const orbitronFont = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--orbitron-font",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${rajdhaniFont.className} ${orbitronFont.className}`}>
        {" "}
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
